keys:
  - &users:
    - &jonatan-yubikey-23839166 age1yubikey1q0uurmnvmdn7x49z84r369t4hv0y7njypwhhzzdwnzxqnst6lcnucvtsl8n
  - &hosts:
    - &local age1qnpen7gae337skxucpx4y2grujh8a0pjl2l4rhp07fz38573ag6sfha3q9
creation_rules:
  - path_regex: secrets/orion/[^/]+\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
          - *jonatan-yubikey-23839166
          - *local
