keys:
  - &users:
    - &jonatan-yubikey-23839166 age1yubikey1q0uurmnvmdn7x49z84r369t4hv0y7njypwhhzzdwnzxqnst6lcnucvtsl8n
  - &hosts:
    - &orion age1qnpen7gae337skxucpx4y2grujh8a0pjl2l4rhp07fz38573ag6sfha3q9
    - &hl-jump age1g7k05egpsaflz0wuppm9fc049cym0xl066uwwzzp2f34drwmg40sj8jnl3
    - &p51 age18ngczvgefy9sdxdkms5dfjvkf9qqz0q7qafmhyhqmnk9f8t9tseqcyg8p8
creation_rules:
  - path_regex: secrets/orion/[^/]+\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
          - *orion
          - *jonatan-yubikey-23839166
  - path_regex: secrets/hl-jump/[^/]+\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
          - *hl-jump
          - *orion
          - *jonatan-yubikey-23839166
  - path_regex: secrets/p51/[^/]+\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
          - *p51
          - *jonatan-yubikey-23839166
