keys:
  - &users:
    - &jonatan-yubikey-23839166 age1yubikey1q0uurmnvmdn7x49z84r369t4hv0y7njypwhhzzdwnzxqnst6lcnucvtsl8n
  - &hosts:
    - &local age1nqzn46xl56a787zantj0w633r5az0wqsswdlf5vsy9tr63wxdedskd3f9n
creation_rules:
  - path_regex: secrets/nixos-orion-7000/[^/]+\.(yaml|yml|json|env|ini)$
    key_groups:
      - age:
          - *jonatan-yubikey-23839166
          - *local
