#!/usr/bin/env bash
# Commit the updated flake.lock on a dated branch, push it, and open a PR
# against main summarising the per-input rev diff.
#
# Requires in the environment:
#   FORGEJO_PR_TOKEN  bot/deploy token with write:repository on the repo
# Requires on disk:
#   /tmp/flake-lock-before.json  pre-update flake.lock (captured earlier)
#   flake.lock                   post-update lock, modified in the worktree
set -euo pipefail

: "${FORGEJO_PR_TOKEN:?open-pr: FORGEJO_PR_TOKEN is unset — add it to the runner SOPS EnvironmentFile}"

date="$(date -u +%Y-%m-%d)"
repo="jonatan/nixos-config"
api="https://forge.fileshare.se/api/v1"
branch="flake-update/${date}"

# Per-input rev diff between HEAD and the updated lock. Walk the root
# inputs, resolve each string alias to its locked node, and emit one line
# per input whose rev moved. Array-valued aliases (nested input overrides)
# are skipped — they are not user-facing inputs.
diff_body="$(
  jq -r --slurpfile before /tmp/flake-lock-before.json '
    . as $root
    | $root.nodes.root.inputs
    | to_entries[]
    | select(.value | type == "string")
    | .key as $name
    | .value as $alias
    | ($before[0].nodes[$alias].locked.rev // "(new)") as $old
    | ($root.nodes[$alias].locked.rev // "(removed)") as $new
    | select($old != $new)
    | "- \($name): \($old[0:12]) → \($new[0:12])"
  ' flake.lock
)"

if [ -z "$diff_body" ]; then
  diff_body='- (no top-level input revs changed; see lock diff for transitive bumps)'
fi

git config user.name 'forgejo-bot'
git config user.email 'forgejo-bot@users.noreply.forge.fileshare.se'

git checkout -b "$branch"
git add flake.lock
git commit -m "chore(flake): update inputs ${date}"

# One-shot authenticated URL — does not persist the token into .git/config.
git push "https://token:${FORGEJO_PR_TOKEN}@forge.fileshare.se/${repo}.git" "$branch"

# The "Resolves security issues" section is reserved for T8 to stamp CVE
# refs into; this workflow leaves it empty.
pr_body="$(
  cat <<EOF
Automated \`nix flake update\` run for ${date}.

### Input changes

${diff_body}

### Resolves security issues

_(none surfaced by this workflow — T8 will populate this section.)_

---

Generated by \`.forgejo/workflows/flake-update.yaml\`. Review and merge once CI is green.
EOF
)"

payload="$(jq -n \
  --arg title "chore(flake): update inputs ${date}" \
  --arg head "$branch" \
  --arg body "$pr_body" \
  '{title:$title, head:$head, base:"main", body:$body}')"

curl --fail --show-error --silent \
  -X POST \
  -H "Authorization: token ${FORGEJO_PR_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "$payload" \
  "${api}/repos/${repo}/pulls"
